---
abstract: 'Create REST-style web service with Riap backend'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Serabi
requires:
  perl: 5.010000
resources:
  homepage: http://metacpan.org/release/Serabi
  repository: http://github.com/sharyanto/perl-Serabi
version: 0.00
